# Generated by Django 4.1.7 on 2024-12-06 04:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("point", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("point", models.IntegerField()),
                ("image", models.ImageField(upload_to="item_images/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("food", "食べ物"),
                            ("good", "グッズ"),
                            ("other", "その他"),
                            ("chiket", "食券"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="point",
            name="date",
            field=models.DateField(default=datetime.date(2024, 12, 6)),
        ),
        migrations.AlterField(
            model_name="point",
            name="points_requested",
            field=models.PositiveIntegerField(
                choices=[
                    (50, "50"),
                    (100, "100"),
                    (150, "150"),
                    (200, "200"),
                    (250, "250"),
                    (300, "300"),
                ],
                verbose_name="ポイント",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
