# Generated by Django 4.1.7 on 2024-12-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point", "0002_item_alter_point_date_alter_point_points_requested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
